# Generated by Django 4.2.3 on 2023-08-15 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_adress_order_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='paid_ammount',
            new_name='paid_amount',
        ),
    ]
